{% set name = "oletools" %}
{% set version = "0.56.2" %}
{% set sha256 = "d6f1c43d00d79bc17e8d2be3eb579170acbaf0d8cbf6b4524447d96c2b8be957" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/decalage2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6

test:
  imports:
    - oletools

about:
  home: https://github.com/decalage2/oletools
  license: BSD-3-Clause
  license_family: BSD
  license_file: oletools/LICENSE.txt
  summary: python tools to analyze MS OLE2 files
  description: oletools is a package of python tools to analyze Microsoft OLE2 files (also called Structured Storage, Compound File Binary Format or Compound Document File Format), such as Microsoft Office documents or Outlook messages, mainly for malware analysis, forensics and debugging.
  doc_url: https://github.com/decalage2/oletools/wiki
  dev_url: https://github.com/decalage2/oletools

extra:
  recipe-maintainers:
    - jan-janssen
    - cshaley
    - sannykr
