{% set name = "oletools" %}
{% set version = "0.53" %}
{% set sha256 = "92779102be64ff84ac0fba829058aa27182be9fda590a6370f71a1ec10e87ded" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/decalage2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - oletools

about:
  home: https://github.com/decalage2/oletools
  license: BSD-3-Clause
  license_family: BSD
  license_file: 'oletools/LICENSE.txt'
  summary: 'python tools to analyze MS OLE2 files'
  description: 
    oletools is a package of python tools to analyze Microsoft OLE2 files
    (also called Structured Storage, Compound File Binary Format or Compound 
    Document File Format), such as Microsoft Office documents or Outlook messages, 
    mainly for malware analysis, forensics and debugging. 
  doc_url: https://github.com/decalage2/oletools/wiki
  dev_url: https://github.com/decalage2/oletools

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
